name: Android tests

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-
      
      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew app:assembleDebug

  test:
    needs: build
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [29]
        flavor: [ Google ]
        shard-index: [ 0 ]
        shard-num: [ 1 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.14.3
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          target: playstore
          disable-animations: true
          script: > 
            ./gradlew app:connectedDebugAndroidTest 
            -Pandroid.testInstrumentationRunnerArguments.numShards=${{ matrix.shard-num }} 
            -Pandroid.testInstrumentationRunnerArguments.shardIndex=${{ matrix.shard-index }}
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: app/build/reports
