name: Android tests

on:
  push:
    branches:
      - master
      
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
        
  #     - uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.gradle/caches/modules-*
  #           ~/.gradle/caches/jars-*
  #           ~/.gradle/caches/build-cache-*
  #         key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
  #         restore-keys: gradle-
      
  #     - name: Build project
  #       working-directory: ${{ env.SAMPLE_PATH }}
  #       run: ./gradlew app:assembleDebug

  instrumented-tests:
    name: Instrumented tests
    runs-on: macos-latest
    timeout-minutes: 25
    strategy:
      matrix:
        api-level: [28]
        shard-index: [ 0 ]
        shard-num: [ 1 ]

    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
      ENABLE_APP_VERSIONING: false

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 15

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            gradle-
      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          profile: Nexus 5X
          script: ./gradlew connectedCheck
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: app/build/reports

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'app/build/outputs/androidTest-results/connected/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: My emulator
        if: always()
        uses: AfzalivE/action-simple-android-emulator@v1.1
      - name: My publish report
        if: always()
        uses: AfzalivE/action-simple-android-emulator@v1.2

