name: Android tests

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: gradle-
      
      - name: Build project
        run: ./gradlew app:assembleDebug

  instrumented-tests:
    name: Instrumented tests
    needs: [build]
    runs-on: macos-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 29 ]
        shard-index: [ 0, 1 ]
        shard-num: [ 2 ]

    env:
      JAVA_TOOL_OPTIONS: -Xmx4g

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            gradle-
#      - name: Run Android instrumented tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 28
#          arch: x86_64
#          profile: Nexus 5X
#          script: ./gradlew connectedCheck -Pandroid.testInstrumentationRunnerArguments.numShards=${{ matrix.shard-num }} -Pandroid.testInstrumentationRunnerArguments.shardIndex=${{ matrix.shard-index }}

      - name: Run emulator
        uses: AfzalivE/action-simple-android-emulator@v1.11
        with:
          script: ./gradlew connectedCheck -Pandroid.testInstrumentationRunnerArguments.numShards=${{ matrix.shard-num }} -Pandroid.testInstrumentationRunnerArguments.shardIndex=${{ matrix.shard-index }}
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-${{ matrix.shard-index }}
          path: app/build/outputs/androidTest-results/connected
  
  publish-report:
      name: Publish Test Report
      needs: [instrumented-tests]
      if: always()
      runs-on: ubuntu-latest
      env:
        JAVA_TOOL_OPTIONS: -Xmx4g

      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v2

        - name: Publish Test Report
          if: always()
          uses: mikepenz/action-junit-report@v2.1.1
          with:
            report_paths: '**/TEST-*.xml'
            github_token: ${{ secrets.GITHUB_TOKEN }} ## Needed to create nice annotations in the job results
